model:
  model_name: "raidium/curia"
  num_classes: 56

dataset_name: "raidium/CuriaBench"
dataset_config: "anatomy-mri"

epochs: 10
batch_size: 64
learning_rate: 0.01
num_workers: 8
eval_steps: 30

output_dir: "./results/anatomy-mri"


