
dataset_name: "raidium/CuriaBench"
dataset_config: "atlas-stroke"

epochs: 60
batch_size: 32
learning_rate: 0.005
num_workers: 8
eval_steps: 200

output_dir: "./results/atlas-stroke"

model:
  model_name: "raidium/curia"
  num_classes: 2
  attention_cfg:
    num_heads: 1
    num_queries: 1
    attention_block: ["self", "cross"]
  num_slices: 1
