dataset_name: "raidium/CuriaBench"
dataset_config: "kneeMRI"

epochs: 500
batch_size: 64
learning_rate: 0.005
num_workers: 8
eval_steps: 30

output_dir: "./results/kneeMRI"

use_feature_caching: true
model:
  model_name: "raidium/curia"
  num_classes: 3
  attention_cfg:
    num_heads: 1
    num_queries: 1
    attention_block: ["self", "cross"]
  num_slices: 3
  use_avgpool_per_slice: false
  use_avgpool_on_the_volume: false
  use_class_token: false
