model:
  model_name: "raidium/curia"
  num_classes: 3

dataset_name: "raidium/CuriaBench"
dataset_config: "neural_foraminal_narrowing"

epochs: 25
batch_size: 64
learning_rate: 0.005
num_workers: 8
eval_steps: 30

output_dir: "./results/neural_foraminal_narrowing"
